Repository tryber/sd-06-project-frontend-online-store, pull requests merged in 2020-09, with the labels that each got.

#33 [GRUPO 5] Montando a HomePage com input e mensagem
  package-lock.json
  package.json
  src/App.js
  src/pages/PaginaInicial.jsx
  src/services/api.js
Labels: code review

#27 requisito 2
  package-lock.json
  package.json
  src/App.js
  src/pages/Home.js
Labels: code review

#20 First commit requirement 2
  src/App.js
Labels: code review

#15 [GRUPO 18] Cria tela de busca
  src/App.js
  src/pages/SearchEngine.js
Labels: code review

#52 [GRUPO 16] - Quindin Online Store
  src/services/api.js
Labels: code review

#23 Fetch API MercadoLivre
  src/services/api.js
Labels: code review

#113 Main group 21 requisito 3 original
  src/services/ShopList.js
Labels: code-review

#132 [Group 30] Add shopping cart - req 3
  src/App.js
  src/HomePage.js
  src/ShoppingCart.js
Labels: code-review

#135 Criando pastas components e pages em src e atualizando imports.
  src/App.js
  src/components/index.js
  src/pages/ShopCart.js
  src/pages/ShopList.js
  src/pages/index.js
Labels: code-review

#144 Implementation of Category List
  src/App.js
  src/components/CategoryList.js
  src/components/Home.js
  src/services/api.js
  src/styles/CategoryList.css
Labels: code-review

#62 Grupo-6-Requisito-1
  src/App.js
  src/services/api.js
Labels: code-review

#49 Group 2 - Implement requirement 1
  src/App.js
  src/services/api.js
Labels: code review

#150 [GRUPO 5] Requisito 4
  src/functions/list_categories.js
  src/pages/PaginaInicial.jsx
Labels: code review

#133 [Group 18] List Category - Req. 4
  README.md
  src/App.js
  src/components/ListCategory.js
  src/pages/Home.js
Labels: code review

#151 feat: search field
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/pages/Home.jsx
  src/pages/index.jsx
Labels: code-review

#128 [Group 18] Product List - Req. 5
  .eslintrc.json
  README.md
  src/App.js
  src/components/FoundProducts.js
  src/pages/SearchEngine.js
  src/services/api.js
Labels: code review

#170 [GRUPO 5] Requisitos 1 ao 5
  src/pages/HomePage.jsx
  src/services/api.js
Labels: code review, code-review

#173 [Group 17][Requisito 4]
  package-lock.json
  src/App.js
  src/components/CategoryDisplay.jsx
Labels: code-review

#93 [GRUPO 7] Requisito 5
  .eslintrc.json
  README.md
  src/components/ProductCard.js
  src/components/ProductList.js
  src/pages/Home.js
  src/services/api.js
Labels: code-review

#96 Grupo-6-requisito-2
  src/App.js
  src/pages/ItemList.js
Labels: code-review

#162 Main group 26 - Requirement 4
  src/Home.js
  src/components/ListCategories.js
Labels: code-review

#163 Main group 21 categories list
  src/pages/ShopList.js
  src/services/api.js
Labels: code-review

#200 Main group 8 request 5
  src/App.js
  src/pages/Home.jsx
  src/pages/ProductCard.jsx
  src/pages/ProductList.jsx
  src/pages/SearchBar.jsx
Labels: code-review

#195 feat: add SearchBar.jsx for requirement 4
  src/pages/SearchBar.jsx
Labels: code-review

#224 Implementation of Filter By Category
  src/components/CategoryList.js
  src/pages/Home.js
Labels: code-review

#216 Group 2 - Implement requirement 4
  .eslintrc.json
  src/App.css
  src/pages/Home.css
  src/pages/Home.jsx
Labels: code-review
